"""Refine foreign keys, nullability, and invoice status constraint

Revision ID: bb3f22575463
Revises: 4c4fa5194993
Create Date: 2026-09-02 22:33:14.647242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3f22575463'
down_revision: Union[str, Sequence[str], None] = '4c4fa5194993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invoices', 'public_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(op.f('invoices_client_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_check_constraint(
        'ck_invoice_status',
        'invoices',
        "status IN ('draft', 'sent', 'paid', 'overdue')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_invoice_status', 'invoices', type_='check')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_client_id_fkey'), 'invoices', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'public_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
